example/src/components/Form/index.stories.js
src/components/Form/RadioGroup/index.jsx
src/components/Form/index.js
src/components/Form/styles.js
src/index.js

Added: Radio Group

---

package.json
src/components/Form/styles.js

Updated: Version
Fixed: Width issue in Radio Buttons

Updated: v0.2.9

---

example/src/components/Form/index.stories.js
package.json
src/components/Form/TextAndSelect/index.jsx
src/components/Form/index.js
src/components/Form/styles.js
src/index.js

- Review and Merge
- Design will need some changes, but for now it will work!

Added: Input with Select

---

example/src/components/Popup/index.stories.js
package.json
src/components/Checkbox/index.jsx
src/components/Popup/index.jsx
src/components/Popup/styles.js
src/index.js

- Added: Popup Component
- Fixed: Checkbox event propagation issue

Added: Popup, Fixed: Checkbox

---

example/src/components/Form/index.stories.js
package.json
src/components/Form/RadioGroup/index.jsx

- Now you can pass default value(must be index) in Radio group component.

Updated: Radio group default value

---

example/src/components/Card/index.stories.js
example/src/components/Popup/index.stories.js
package.json
src/components/Card/index.jsx
src/components/Card/styles.js
src/components/Popup/index.jsx
src/components/Popup/styles.js
src/index.js

- No conflicts
- Version upgraded

Added: Popup and Card(C911)

---

example/src/components/Tiles/index.stories.js
package.json
src/assets/icons/ArrowRightIcon.jsx
src/assets/icons/index.js
src/components/Tiles/ButtonTile.jsx
src/components/Tiles/DashboardTile.jsx
src/components/Tiles/index.jsx
src/components/Tiles/styles.js
src/index.js

feat: Button Tile and Dashboard Tile

---

package.json
src/components/Tiles/ButtonTile.jsx
src/components/Tiles/styles.js

- No conflicts
- Package published
- Tag: v0.5.8

refactor: Updated icons sizes and padding

---

example/src/components/Checkbox/index.stories.js
package.json
src/assets/icons/TickIcon.jsx
src/components/Checkbox/index.jsx
src/components/Checkbox/styles.js

This PR fixes some checkbox issues:
Before:
```js
const [checked, setChecked] = React.useState(true)
return (
<React.Fragment>
<Checkbox
checked={ checked }
onChange={ (checked) => setChecked(checked) }
/> 
<span>Yes, I love Dailykit!</span>
</React.Fragment>
)
```
Now:
```js
const [checked, setChecked] = React.useState(true)
return (
<React.Fragment>
<Checkbox id='label' checked={checked} onChange={setChecked}>
Yo, this is a label!
</Checkbox>
</React.Fragment>
)
```

fix: checkbox issues

---

example/src/components/List/index.stories.js
example/src/global.css
package.json
src/components/List/ListItem/index.jsx
src/components/List/ListItem/styled.js
src/components/List/index.jsx
src/components/List/styled.js
src/components/button/styles.js
src/hooks/index.js
src/hooks/useMultiList.js
src/hooks/useSingleList.js
src/index.js

This PR adds List component to the library
**Components:**
- Single Select List
- Multi Select List
- List Items
- SSL1
- SSL2
- SSL22
- MSL1
- MSL2
- MSL31
- MSL111
- MSL1101

feat(component): List

---

package.json
src/components/Checkbox/index.jsx
src/components/Checkbox/styles.js
src/components/List/ListItem/styled.js

fix: checkbox

---

src/components/Tunnel/styled.js

Current behavior : 
-  Tunnel is not  responsive 
Desired behavior: 
- Tunnel should be  responsive 
@FAsami

feat(responsiveness): make tunnel responsive

---

example/src/components/SectionTabs/index.stories.js
src/components/SectionTabs/index.jsx
src/components/Tabs/index.jsx

Desired behavior : 
Tabs should be responsive

feat(responsiveness): make horizontal and vertical tabs responsive

---

example/src/components/Dropdown/index.stories.js
package.json
src/components/Dropdown/Multi/index.jsx

- Added DefaultOptions and DefaultIds prop in the multi dropdown component

feat:added defaultOptions and defaultIds in multi dropdown

---

example/src/components/AnchorNavigationMenu/index.stories.js
package.json
src/components/AnchorNavigationMenu/index.js
src/components/AnchorNavigationMenu/style.js
src/index.js
yarn.lock

- AnchorNavigationMenu component added

feat(revamp) : anchor menu added

---

package.json
src/components/Tunnel/styled.js

- Added padding and overflow to the tunnels to show the content bottom of it.

fix  - Added padding to the tunnels

---

package.json
src/components/Dropdown/Multi/index.jsx
src/components/Dropdown/Multi/styles.js

Fixed issues of return deselect option
add button for clear selected data

fix:deselect option and feat add clear selected option

---

example/src/components/Checkbox/index.stories.js
package.json
src/components/Checkbox/index.jsx

feat: added minus icon in checkbox

---

example/src/components/Button/index.stories.js
package.json
src/components/DropdownButton/index.js
src/components/DropdownButton/styles.js
src/index.js

feat: added dropdown button

---

package.json
src/components/DropdownButton/styles.js

changed css for the text of button

fix: dropdown button text css changed

---

package.json
src/components/Text/index.jsx

Passed all props in all variants

fix: passed all props

---

package.json
src/components/Form/styles.js

Removed the min width from SearchBox

fix: removed min width

---

package.json
src/components/Tunnel/index.jsx

- Tunnel height changed to fit with new UI

fix-tunnel height changed
